#!/usr/bin/env sh

# execute pre-run scripts
# will probably make a kagami built-in feature later
for f in "$DOC_ROOT/.scripts/"*; do echo "Pre-run: '$f'"; $f; done

# unsetting document root will rewrite links starting from /
unset DOC_ROOT

AUTHOR='microsounds'
SITE_TITLE='sentimental µsounds'
SITE_SUBTITLE='the echoes of time stand still'
SITE_HOST='https://microsounds.github.io'
GIT_REMOTE='https://github.com/microsounds'
ACCENT_COLOR='#E2FAF9'

# copyright years
YEAR="2015-$(date '+%Y')"
CC_BY_SA='https://creativecommons.org/licenses/by-sa/4.0'
GNU_GPL='https://www.gnu.org/licenses/gpl-3.0'

# moonphase date function
# dark background, invert glyphs
# append U+FE0E to glyphs to force display as text only
TZ='America/Los_Angeles'
DATE_FUNCTION='moonphase-date -iyh'
