#!/usr/bin/env sh
# unset to set document root to /
unset DOC_ROOT

AUTHOR='microsounds'
SITE_TITLE='sentimental µsounds'
SITE_SUBTITLE='the echoes of time stand still'
SITE_HOST='https://microsounds.github.io'
GIT_REMOTE='https://github.com/microsounds'

# functions
YEAR="$(date '+%Y')"

# moon phase date
INVERT=1
DATE_FUNCTION='moonphase_date'
moonphase_date() (
	[ ! -z "$1" ] || [ "$1" -eq "$1" ] 2> /dev/null || return 1
	# calculate days since a specific new moon
	# divide by length of lunar cycle
	# express currently elapsed cycle progress in percent
	known=633381600 # Jan 26th, 1990 was a new moon
	cycle=$(echo "scale=2; (($1 - $known) / 86400) / 29.53" | bc)
	cycle=${cycle#*.} # absolute value
	# map cycle progress to an available glyph
	# reverse video: switch new/full moon glyphs for use with dark backgrounds
	phases='🌑 🌒 🌓 🌔 🌕\n🌕 🌖 🌗 🌘 🌑'
	map=$(((${cycle#0} / 10) + 1))
	moon=$(echo "$phases" | sort ${INVERT:+-r} | tr ' ' '\n' \
		| tail -n +$map | head -n 1)

	# current date
	timest=$(date -d "1970-01-01 UTC $1 seconds" '+%-e %a, %b x, %Y')
	day="${timest%% *}"
	case $day in
		1 | [!1]1) day="${day}st";;
		2 | [!1]2) day="${day}nd";;
		3 | [!1]3) day="${day}rd";;
		*) day="${day}th"
	esac
	echo "$moon ${timest#* }" | sed "s/x/$day/"
)
